export const TABLE_CELL_RESIZE = 'TABLE_CELL_RESIZE';
export const TABLE_ROW_RESIZE = 'TABLE_ROW_RESIZE'
export const CELLS_VALUES = 'CELLS_VALUES';
export const APPLY_STYLE = 'APPLY_STYLE';
export const CHANGE_CELL_STYLES = 'CHANGE_CELL_STYLES';
export const CHANGE_TITLE = 'CHANGE_TITLE';